### ISSUE TITLE
deployed wordpress with now-php

### ISSUE THREAD

**Issue by fydy** [juicyfx/vercel-php#36]
I deployed wordpress with now-php. When running, it shows too many redirects. 
![image](https://user-images.githubusercontent.com/39726855/70965016-29cc6d80-20c9-11ea-864d-71b271b849d9.png)
My now.json is
```
{
  "version": 2,
  "builds": [
    { "src": "index.php", "use": "now-php" },
    { "src": ".htaccess", "use": "@now/static" }
  ],
  "routes": [
    { "src": "/(.*)", "dest": "index.php" } 
  ],
  "regions": ["icn1"]
}
```

**Comment by f3l1x** [comment]
Hi @fydy. Could you please point me a repository? I would help.

**Comment by fydy** [comment]
@f3l1x The code repository I deployed: https://github.com/fydy/demo_wordpress

For security, I used the free mysql database: remotemysql.com

thank you

**Comment by Apokly** [comment]
Hi @fydy @f3l1x ,

Is this fix ? Do you have a solution ?

**Comment by f3l1x** [comment]
Hi @Apokly. I've been working on bigger issue #48 and #47. Didn't fix it yet.

**Comment by f3l1x** [comment]
Hi. I have added wordpress example and hit also `Too many redirects`.

![image](https://user-images.githubusercontent.com/538058/76561033-c45b0380-64a2-11ea-95e3-c9f20511db20.png)

https://github.com/juicyfx/now-examples/tree/master/php-wordpress

**Comment by f3l1x** [comment]
It looks like wordpress is not ready for PHP development server or need extra routing configuration. I appreciate some help.

**Comment by fydy** [comment]
@f3l1x This is the [now-wordpress index.js code](https://github.com/fydy/now-wordpress/blob/master/index.js), but now nodejs8.10 is no longer supported. Can it be integrated into now-php? This may be able to run wordpress normally.

**Comment by kjbrum** [comment]
Anyone had any luck getting WordPress running with this? I keep getting the "Too Many Redirects" error.

**Comment by f3l1x** [comment]
From my point of view, wordpress is not working on serverless smooth. I would recommend some other platform.

**Comment by bradleyg** [comment]
Anybody had anymore luck with this since 2020?
Seems so close to working..

**Comment by f3l1x** [comment]
Nope. Wordpress is basically not suitable for this.

**Comment by f3l1x** [comment]
Closing it. I don't this this will happen any soon.
